FROM mysql:latest
ENV MYSQL_DATABASE test
ENV MYSQL_ROOT_PASSWORD mypassword
# Add the content of the sql-scripts/ directory to your image
# All scripts in docker-entrypoint-initdb.d/ are automatically
# executed during container startup
COPY mysql-server/sql-scripts/ /docker-entrypoint-initdb.d/
