FROM alpine-jdk:base
MAINTAINER javaonfly
COPY config-server/target/configserver-0.0.1-SNAPSHOT.jar /opt/lib/
RUN mkdir /var/lib/config-repo
COPY config-server/config-repo /var/lib/config-repo
RUN ls /var/lib/config-repo
ENTRYPOINT ["/usr/bin/java"]
CMD ["-jar", "/opt/lib/configserver-0.0.1-SNAPSHOT.jar"]
VOLUME /var/lib/config-repo
EXPOSE 9090
