FROM alpine-jdk:base
MAINTAINER javaonfly
RUN apk --no-cache add netcat-openbsd
COPY product-service/target/productservice-0.0.1-SNAPSHOT.jar /opt/lib/
COPY product-service/ProductService-entrypoint.sh /opt/bin/ProductService-entrypoint.sh
RUN chmod 755 /opt/bin/ProductService-entrypoint.sh
EXPOSE 8080
