FROM alpine-jdk:base
MAINTAINER javaonfly
RUN apk --no-cache add netcat-openbsd
COPY dashboard/target/dashboard-0.0.1-SNAPSHOT.jar /opt/lib/
COPY dashboard/dashboard-entrypoint.sh /opt/bin/dashboard-entrypoint.sh
RUN chmod 755 /opt/bin/dashboard-entrypoint.sh
EXPOSE 8081
