FROM alpine-jdk:base
MAINTAINER javaonfly
RUN apk --no-cache add netcat-openbsd
COPY order-service/target/orderservice-0.0.1-SNAPSHOT.jar /opt/lib/
COPY order-service/OrderService-entrypoint.sh /opt/bin/OrderService-entrypoint.sh
RUN chmod 755 /opt/bin/OrderService-entrypoint.sh
EXPOSE 8080
