FROM alpine-jdk:base
MAINTAINER javaonfly
COPY service-discovery/target/servicediscovery-0.0.1-SNAPSHOT.jar /opt/lib/
ENTRYPOINT ["/usr/bin/java"]
CMD ["-jar", "/opt/lib/servicediscovery-0.0.1-SNAPSHOT.jar"]
EXPOSE 9091
